# Generated by Django 4.1.5 on 2023-01-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisplayModels',
            new_name='DisplayModel',
        ),
    ]
